services:
  postgres:
    image: postgres:15
    container_name: java-postgres
    environment:
      - 'POSTGRES_DB=TaskManagementSystems'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile
    container_name: java-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy  # Запуск backend только если БД готова
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TaskManagementSystems
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres