CREATE TABLE IF NOT EXISTS "users"
(
    id       BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "name"   VARCHAR(32) UNIQUE NOT NULL,
    password VARCHAR(32) NOT NULL,
    email    VARCHAR(100) UNIQUE NOT NULL,
    role     VARCHAR NOT NULL
);
